### ISSUE TITLE
Cannot get validation to work

### ISSUE THREAD

**Issue by mdzhigarov** [andrew-waters/insomnia.plugin.validator#1]
Hey man, this plugin looks quite useful.:)
I was thrilled to find that somebody has come up with the idea of integrating insomnia with swagger.

But I cannot get this to work.
My endpoint is at:
`http://localhost:8282/iaas/machines`
My spec looks like:
```
{
	"spec": {
		"base": "http://localhost:8282/iaas",
		"enabled": true,
		"path": "/Users/mdzhigarov/dev/git/iaas-api/service/target/classes/swagger-multicloud.json"
	}
}
```

In swagger-multicloud.json I have defined a required property called "myTestProperty":

```
"Machine" : {
      "type" : "object",
      "required" : [ "myTestProperty", "externalRegionId", "externalZoneId", "flavor", "powerState", "selfLink", "specificationLink" ],
      "properties" : {
        "myTestProperty" : {
          "name" : {
            "type" : "string",
            "example" : "asd",
            "description" : "asd"
          }
        },
        ...
```
... and I intentionally made my endpoint not return it.

When I execute GET on my endpoint, Insomnia simply returns the result. The plugin doesn't fire any validation warnings or anything like that. 
What am I missing?

**Comment by andrew-waters** [comment]
Hey @mdzhigarov  - sorry I missed this! What is the response from your API fo the GET call?

**Comment by andrew-waters** [comment]
@mdzhigarov going to close this as I haven't heard back. Feel free to reopen if you need help.
